name: CI/CD Pipeline - Vaishnavi

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t vaishnavi-devops:latest .

      - name: Save Docker image as artifact
        run: docker save vaishnavi-devops:latest | gzip > vaishnavi-devops.tar.gz

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: vaishnavi-devops.tar.gz

