name: Deploy Docker App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t vaishnavi-devops-app .

      - name: Run container
        run: docker run -d -p 8080:80 vaishnavi-devops-app

